# Generated by Django 5.2 on 2026-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_add_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, verbose_name="카테고리명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="상세설명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="landing_page_image",
            field=models.ImageField(
                upload_to="landing/", verbose_name="상품설명이미지"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="상품이름"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(verbose_name="가격"),
        ),
        migrations.AlterField(
            model_name="productcapacity",
            name="capacity_name",
            field=models.CharField(max_length=10, verbose_name="용량"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/image/", verbose_name="제품이미지"
            ),
        ),
    ]
