# Generated by Django 5.2 on 2026-05-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_restructure_catalog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="product",
        ),
        migrations.AddField(
            model_name="brand",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="classification",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="products.classification",
            ),
            preserve_default=False,
        ),
    ]
