# Generated by Django 5.2 on 2026-06-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_model_product_brand_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="product",
        ),
        migrations.AddField(
            model_name="model",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
