# Generated by Django 5.2 on 2026-06-07 11:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_brand_product_model_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="path",
            field=models.ImageField(
                upload_to=products.models.get_image_upload_path,
                verbose_name="제품 이미지",
            ),
        ),
    ]
